### ISSUE TITLE
Zrobić design aplikacji w penpot

### ISSUE THREAD

**Issue by Pokrzw** [Pokrzw/Plant-Tracker#2]

**Comment by JagnaJuras** [comment]
Ogólny design jest gotowy w PenPot - jest jeszcze parę elementów, które muszę poprawić i które musimy uzgodnić, ale to już w ciągu tygodnia. Dodam sobie na Asanie to, co jeszcze chcę zmienić. Zajmę się teraz konkretnym design systemem.
